# frozen_string_literal: true

source "https://rubygems.org"

# Fastlane dependencies
gem "fastlane", "~> 2.215"

# Android-specific plugins (optional)
# gem "fastlane-plugin-play_console", "~> 0.1"

plugins_path = File.join(File.dirname(__FILE__), 'plugins')
